// frontend/src/App.svelte
<script lang="ts">
  import SplitPane from './lib/components/SplitPane.svelte'
  import TimerBar from './lib/components/TimerBar.svelte'
  import TimerModal from './lib/components/TimerModal.svelte'
  import WorkoutEditor from './lib/components/WorkoutEditor.svelte'
  import VideoPlayer from './lib/components/VideoPlayer.svelte'
  import { timer } from './lib/stores/timer.svelte'
  import { session } from './lib/sync/session.svelte'
  import { onMount } from 'svelte'

  let showModal = $state(false)

  function onKeydown(e: KeyboardEvent) {
    const target = e.target as HTMLElement
    if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable) return
    if (e.code === 'Space') {
      e.preventDefault()
      timer.toggle()
    } else if (e.code === 'KeyR') {
      timer.reset()
    } else if (e.code === 'KeyM') {
      showModal = !showModal
    }
  }

  onMount(() => {
    session.joinFromLocation()
  })
</script>

<svelte:window onkeydown={onKeydown} onhashchange={() => session.joinFromLocation()} />

<div id="layout">
  <SplitPane orientation="rows" initial={15} min={5} storageKey="wodch-split-timer">
    {#snippet a()}
      <TimerBar onOpenModal={() => (showModal = true)} />
    {/snippet}
    {#snippet b()}
      <SplitPane orientation="columns" initial={50} min={10} storageKey="wodch-split-editor">
        {#snippet a()}
          <WorkoutEditor />
        {/snippet}
        {#snippet b()}
          <VideoPlayer />
        {/snippet}
      </SplitPane>
    {/snippet}
  </SplitPane>
</div>

{#if showModal}
  <TimerModal onClose={() => (showModal = false)} />
{/if}

<style>
  #layout {
    height: 100%;
  }
</style>

// src/App.vue
<template>
  <div id="app">
    <Splitpanes horizontal class="root-panes">
      <!-- Zeile 1: Timer-Leiste -->
      <Pane :size="15" :min-size="5">
        <TimerBar @open-modal="showModal = true" />
      </Pane>

      <!-- Zeile 2: Editor + Video -->
      <Pane :size="85">
        <Splitpanes class="inner-panes">
          <Pane :size="50">
            <WorkoutEditor />
          </Pane>
          <Pane :size="50">
            <VideoPlayer />
          </Pane>
        </Splitpanes>
      </Pane>
    </Splitpanes>

    <TimerModal v-if="showModal" @close="showModal = false" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Splitpanes, Pane } from 'splitpanes'
import TimerBar from './components/TimerBar.vue'
import WorkoutEditor from './components/WorkoutEditor.vue'
import VideoPlayer from './components/VideoPlayer.vue'
import TimerModal from './components/TimerModal.vue'
import { useTimerStore } from './stores/timerStore'
import { useSession, extractSessionId, sessionId } from './composables/useSession'

const store = useTimerStore()
const { joinSession } = useSession()
const showModal = ref(false)

function onKeydown(e: KeyboardEvent) {
  const target = e.target as HTMLElement
  if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable) return

  if (e.code === 'Space') {
    e.preventDefault()
    store.toggle()
  } else if (e.code === 'KeyR') {
    store.reset()
  } else if (e.code === 'KeyM') {
    showModal.value = !showModal.value
  }
}

function onHashChange() {
  const id = extractSessionId()
  if (id && id !== sessionId.value) joinSession(id)
}

onMounted(() => {
  store.start()
  document.addEventListener('keydown', onKeydown)
  window.addEventListener('hashchange', onHashChange)

  const id = extractSessionId()
  if (id) joinSession(id)
})

onUnmounted(() => {
  document.removeEventListener('keydown', onKeydown)
  window.removeEventListener('hashchange', onHashChange)
})
</script>

<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body, #app { height: 100%; background: #000; color: #fff; font-family: monospace; }

.root-panes { height: 100%; }
.inner-panes { height: 100%; }

/* splitpanes Handles */
.splitpanes--horizontal > .splitpanes__splitter {
  height: 4px !important;
  background: #333 !important;
  z-index: 1;
}
.splitpanes--vertical > .splitpanes__splitter {
  width: 12px !important;
  background: #0d0d0d !important;
  z-index: 1;
}
.splitpanes__splitter:hover {
  background: #555 !important;
}
</style>
